### ISSUE TITLE
Sharing terminal width with elevated processes

### ISSUE THREAD

**Issue by jviotti** [tehsenaus/windosu#4]
Hi, I'm having some issues running a script that uses [inquirer](https://github.com/SBoudrias/Inquirer.js) with `windosu`.

The problem is that within `windosu` context, `inquirer` is unable to correctly get the width of the terminal, which is being calculated with [cli-width](https://github.com/knownasilya/cli-width).

I've [submitted a PR to inquirer to set a default width of 80 characters](https://github.com/SBoudrias/Inquirer.js/pull/297) which seems to work fine in most cases, however there is a way to make `windosu` share the correct width with the script it executes:

`cli-width` (in the latest version, v1.1.0), [attempts to read the width from an environment variable](https://github.com/knownasilya/cli-width/pull/5) (`CLI_WIDTH`) before going for the default value.

This gives us an opportunity to calculate the width from `windosu` and pass it to child processes like this:

```js
var cliWidth = require('cli-width');
var child_process = require('child_process');

child_process.spawn('foo', [ 'bar' ], {
    env: {
        CLI_WIDTH: cliWidth()
    }
});
```

This way, scripts being called with `windosu` have a way to inherit this value, even if not written in NodeJS.

What do you think?

I'll send a PR for demonstration purposes later today, once I have access to a Windows PC.

**Comment by tehsenaus** [comment]
Sure, this sounds very reasonable. I look forward to seeing the pull request!

**Comment by jviotti** [comment]
@tehsenaus PR sent!
