### ISSUE TITLE
Inquirer list never exits on windosu

### ISSUE THREAD

**Issue by jviotti** [tehsenaus/windosu#7]
I'm having a strange issue when running an [inquirer](https://github.com/SBoudrias/Inquirer.js) list on `windosu`. The process never exits.

For example:

``` javascript
// test.js
var inquirer = require('inquirer');

inquirer.prompt([
    {
        type: 'list',
        name: 'foo',
        message: 'Hello',
        choices: [ 'Foo', 'Bar' ] 
    }
], function(answers) {
   console.log(answers.foo);
});
```

When running the script with `sudo`, the script runs fine, but the process never exits (the `windosu` callback never gets called). This behaviour is not reproducible when running the script directly.

I've been trying to debug the issue for hours, but have no idea what could be causing this. I was hoping you could provide more insight about how `windosu` works and what might be causing inquirer to not run as expected (maybe something along `readline`?).

**Comment by jviotti** [comment]
Turns out it happens with all prompts.

**Comment by jviotti** [comment]
I can force the exit with `process.exit()` on completion, which seems to work fine. Do you think there is a reliable way for a script to know if it's running under `windosu`?

**Comment by tehsenaus** [comment]
Hi, apologies for the delay. I suspect this is to do with pipes not being closed when they should...

Internally windosu creates a Windows named pipe to bridge the elevated and non-elevated shells (see pipe.latte).

Perhaps inquirer behaves differently when running on a TTY vs a pipe?

**Comment by jviotti** [comment]
Closing stale issues
